name: release

on:
  release:
    types: [released]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release-artifact:
    runs-on: ubuntu-latest
    steps:
      - id: transglobe-framework-release
        uses: shihyuho/go-jenkins-trigger@v1
        with:
          jenkins-url: "${{ secrets.JENKINS_URL }}"
          jenkins-user: "${{ secrets.JENKINS_USER }}"
          jenkins-pat: "${{ secrets.JENKINS_PAT }}"
          insecure: "true"
          job: "${{ github.action }}"
          params: "ref=${{ github.ref }}"
